### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by suku-h** [pianomansam/serverless-offline-stepfunctions-plugin#1]
I executed the test in library. The following is the error when I checked the execution using the describeExecution api:
`{ executionArn: 'arn:aws:states:local:012345678901:execution:Test:5b0fbcec-81f9-4e31-b4e4-24ebdc707a6f',
  stateMachineArn: 'arn:aws:states:us-east-1:012345678901:stateMachine:Test',
  name: '5b0fbcec-81f9-4e31-b4e4-24ebdc707a6f',
  status: 'FAILED',
  startDate: 2019-09-05T09:50:14.306Z,
  stopDate: 2019-09-05T09:50:14.314Z,
  input: '{"first":1,"second":2}' }
`

I added the accountId to the custom:
`custom:
  offlineStepFunctions:
    accountId: 012345678901
    port: 4584
    host: localhost
    functions:
      HelloWorld: example
`

Rest everything is unchanged. 

The second step function `TestString` works fine. It appears that States of type Task are failing

**Comment by pianomansam** [comment]
@suku-h can you provide some more details on your process? Here's the process I went through and it succeeds for me:

add `accountId: 012345678901`

```
cd tests
yarn
yarn sls offline
(in another window)
aws stepfunctions --endpoint http://localhost:4584 start-execution --state-machine-arn "arn:aws:states:us-east-1:012345678901:stateMachine:Test" --input '{"first": 1, "second": 2}'
```

**Comment by suku-h** [comment]
I apologise. I forgot to mention that I got the error when I passed the executionArn to the describeExecution api. That is when I got the error

P.S.: I have updated the question

**Comment by pianomansam** [comment]
@suku-h Thanks for providing more details. I'm still not able to reproduce, though. 

```
aws stepfunctions --endpoint http://localhost:4584 describe-execution --execution-arn "arn:aws:states:local:012345678901:execution:Test:4c26a7e6-0031-4b7b-b0e2-5c405263436d"
{
    "status": "SUCCEEDED", 
    "startDate": 1567775077.012, 
    "name": "4c26a7e6-0031-4b7b-b0e2-5c405263436d", 
    "executionArn": "arn:aws:states:local:012345678901:execution:Test:4c26a7e6-0031-4b7b-b0e2-5c405263436d", 
    "stateMachineArn": "arn:aws:states:us-east-1:012345678901:stateMachine:Test", 
    "stopDate": 1567775077.058, 
    "output": "{\"isOffline\":true,\"stageVariables\":{}}", 
    "input": "{}"
}
```

To get more debugging output from serverless offline, try exporting a few environment variables.

```
export SLS_DEBUG=*
export DEBUG=stepfunctions-local:*
```

This will give you debugging info from both serverless offline and stepfunctions-local. Hopefully, that will show you where the execution is failing.

**Comment by suku-h** [comment]
The lambda is failing because of an `Unknown Error`

Here is the output on `sls offline`
 ```
  stepfunctions-local:log { stateMachines: 
  stepfunctions-local:log    [ { stateMachineArn: 'arn:aws:states:us-east-1:012345678901:stateMachine:Test',
  stepfunctions-local:log        definition: [Object],
  stepfunctions-local:log        creationDate: 1568017503.642,
  stepfunctions-local:log        roleArn: 'arn:aws:iam::012345678901:role/service-role/MyRole',
  stepfunctions-local:log        name: 'Test',
  stepfunctions-local:log        status: 'ACTIVE' },
  stepfunctions-local:log      { stateMachineArn: 'arn:aws:states:us-east-1:012345678901:stateMachine:TestString',
  stepfunctions-local:log        definition: [Object],
  stepfunctions-local:log        creationDate: 1568017503.675,
  stepfunctions-local:log        roleArn: 'arn:aws:iam::012345678901:role/service-role/MyRole',
  stepfunctions-local:log        name: 'TestString',
  stepfunctions-local:log        status: 'ACTIVE' } ],
  stepfunctions-local:log   executions: [],
  stepfunctions-local:log   activities: [] }
```

The following is the script to invoke the step function

```
const AWS = require('aws-sdk');

const stepFunctions = new AWS.StepFunctions({
  endpoint: `http://localhost:4584`,
  region: `us-east-1`
});

const stateMachineArn = 'arn:aws:states:us-east-1:012345678901:stateMachine:Test'

let executionArn
async function executeStepFn() {
  try {
    let op = await stepFunctions
      .startExecution({
        stateMachineArn
      }).promise()

    executionArn = op.executionArn
    console.log('executionArn', executionArn)
  } catch (err) {
    console.log('err', err)
  }
}

executeStepFn()

setTimeout(async () => {
  let execution = await stepFunctions.describeExecution({ executionArn }).promise()
  console.log('execution', execution)

  let history = await stepFunctions.getExecutionHistory({
    executionArn,
    maxResults: 3,
    reverseOrder: true
  }).promise()

  console.log('history', JSON.stringify(history))
}, 5000)

```

This is the output of the script:

```
executionArn arn:aws:states:local:012345678901:execution:Test:714f763e-5eae-4d88-bf59-1df2f7842252
execution { executionArn: 'arn:aws:states:local:012345678901:execution:Test:714f763e-5eae-4d88-bf59-1df2f7842252',
  stateMachineArn: 'arn:aws:states:us-east-1:012345678901:stateMachine:Test',
  name: '714f763e-5eae-4d88-bf59-1df2f7842252',
  status: 'FAILED',
  startDate: 2019-09-09T08:29:28.050Z,
  stopDate: 2019-09-09T08:29:28.077Z,
  input: '{}' }
history {"events":[{"timestamp":"2019-09-09T08:29:28.076Z","type":"ExecutionFailed","id":6,"previousEventId":5,"executionFailedEventDetails":{"error":"Bad Request","cause":"UnknownError"}},{"timestamp":"2019-09-09T08:29:28.074Z","type":"LambdaFunctionFailed","id":5,"previousEventId":4,"lambdaFunctionFailedEventDetails":{"error":"Bad Request","cause":"UnknownError"}},{"timestamp":"2019-09-09T08:29:28.054Z","type":"LambdaFunctionStarted","id":4,"previousEventId":3}],"nextToken":"eyJuZXh0VG9rZW4iOm51bGwsImJvdG9fdHJ1bmNhdGVfYW1vdW50IjozfQ=="}

```

This is the debug logs of serverless offline:

```
stepfunctions-local:log   executions: 
  stepfunctions-local:log    [ { name: '714f763e-5eae-4d88-bf59-1df2f7842252',
  stepfunctions-local:log        input: {},
  stepfunctions-local:log        executionArn: 'arn:aws:states:local:012345678901:execution:Test:714f763e-5eae-4d88-bf59-1df2f7842252',
  stepfunctions-local:log        startDate: 1568017768.05,
  stepfunctions-local:log        stateMachineArn: 'arn:aws:states:us-east-1:012345678901:stateMachine:Test',
  stepfunctions-local:log        status: 'FAILED',
  stepfunctions-local:log        events: [Array],
  stepfunctions-local:log        stopDate: 156801776
```

I believe there is some credential or config that you have that I haven't specified. I am always asked to enter my region and accountId which you may have specified in your aws config. Is there something that I am missing?

**Comment by pianomansam** [comment]
@suku-h is the region in your `serverless.yml` also set to `us-east-1`?

**Comment by suku-h** [comment]
I have the following aws config:

```
{
  expired: false,
  expireTime: null,
  refreshCallbacks: [],
  accessKeyId: 'AKIAJ************,
  sessionToken: undefined,
  filename: undefined,
  profile: 'default',
  disableAssumeRole: true,
  preferStaticCredentials: false,
  tokenCodeFn: null,
  httpOptions: null }
```

I did not set the region to `us-east-1` in yaml but I have specified it in the step function call.

These are the parameters used to build the step function on executing `sls offline` 

```
{ endpoint: 'http://localhost:4584',
  region: 'us-east-1',
  accessKeyId: 'AKIAJP********',
  secretAccessKey: 'oRs***********************' }
```

**Comment by pianomansam** [comment]
@suku-h it looks like it's trying to call the lambda in the `local` region while calling the stepfunctions in the `us-east-1` region. There may be a bug in setting the correct region. Are you setting the `local` region somewhere? Try manually setting the region to `us-east-1` and see if it works.

**Comment by suku-h** [comment]
The only place I have set region was while invoking the step function as I showed above.

**Comment by suku-h** [comment]
I tried that too. But it did nothing. My only hint that there is a different behaviour is that when I call the step function it asks for region

**Comment by pianomansam** [comment]
@suku-h unfortuantely, at this point, I'm stuck at the inability to reproduce your issue.

**Comment by suku-h** [comment]
I deleted the project and recloned it. Now it is working after setting the region. Some debugging that I was doing must've caused an issue
